# Generated by Django 5.1.1 on 2024-10-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
